baseurl: "/"
permalink: "/:categories/:title/"
markdown: "kramdown"
excerpt_separator: ""
relative_permalinks: false
title: "JayGreentree.Live"
github: ''

prose:
  rooturl: "announcements/_posts"
  siteurl: ""
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "announcement"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
